# Generated by Django 4.1.7 on 2023-02-24 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("inscricao", models.CharField(max_length=255, unique=True)),
                ("data_apuracao", models.DateField()),
                ("banco", models.CharField(max_length=255)),
                ("is_a_vista", models.BooleanField()),
                (
                    "entrada",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14),
                ),
                ("numero_parcelas", models.SmallIntegerField(blank=True, null=True)),
                ("arquivo", models.FileField(upload_to="faturas/")),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
