# Generated by Django 4.1.7 on 2023-02-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatura",
            name="is_a_vista",
            field=models.BooleanField(default=True),
        ),
    ]
