# Generated by Django 4.1.7 on 2023-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_fatura_arquivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fatura",
            name="entrada",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
