# Generated by Django 4.1.7 on 2023-02-24 04:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth_regularize", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="last_name",
        ),
    ]
