# Generated by Django 4.1.7 on 2023-02-24 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):
    dependencies = [
        ("auth_regularize", "0002_remove_usuario_first_name_remove_usuario_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DadosUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=255)),
                ("razao_social", models.CharField(blank=True, max_length=255)),
                ("cnpj", django_cpf_cnpj.fields.CNPJField(max_length=18, unique=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
