# Generated by Django 4.1.7 on 2023-02-24 05:51

from django.db import migrations
import django_cpf_cnpj.fields


class Migration(migrations.Migration):
    dependencies = [
        ("auth_regularize", "0003_dadosusuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dadosusuario",
            name="cnpj",
            field=django_cpf_cnpj.fields.CNPJField(
                blank=True, max_length=18, null=True, unique=True
            ),
        ),
    ]
