# Generated by Django 4.1.7 on 2023-02-28 02:47

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_regularize", "0004_alter_dadosusuario_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dadosusuario",
            name="cnpj",
            field=localflavor.br.models.BRCNPJField(
                blank=True, max_length=18, null=True, unique=True
            ),
        ),
    ]
