# Generated by Django 4.1.7 on 2023-02-28 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_regularize", "0005_alter_dadosusuario_cnpj"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dadosusuario",
            name="razao_social",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
